---
- name: Workstation setup (macos)
  hosts: localhost
  connection: local
  become: true
  become_user: kunta

  tasks:
    - name: Install homebrew packages
      community.general.homebrew:
        name:
          - gpg
          - podman
          - podman-compose
          - zsh
          - zsh-completions
          - zsh-autosuggestions
          - oh-my-posh
          - asdf
          - vim
    - name: Install homebrew casks
      community.general.homebrew_cask:
        name:
          - visual-studio-code
          - 1password
          - logi-options+
          - intune-company-portal
          - microsoft-teams
          - rectangle
          - alt-tab
          - ghostty
          - raycast
          - betterdisplay
          - stats
          - font-iosevka
          - firefox
          - google-chrome
          - brave-browser
          - zen-browser
          - microsoft-edge
          - karabiner-elements
    - name: Configure keybindings
      ansible.builtin.copy:
        src: files/karabiner.json
        dest: ~/.config/karabiner
        force: yes
    - name: Install oh-my-zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: ~/.zshrc
    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        version: v0.7.0
    - name: Enable zsh plugins
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        regexp: '^plugins='
        line: plugins=(git asdf zsh-autosuggestions)
    - name: Install asdf-vm
      ansible.builtin.git:
        repo: 'https://github.com/asdf-vm/asdf'
        dest: ~/.asdf
        version: v0.14.1
    - name: Adding asdf-vm plugins
      ansible.builtin.shell: "asdf plugin add {{ item.plugin_name }}"
      args:
        creates: "~/.asdf/plugins/{{ item.plugin_name }}"
      loop:
        - { plugin_name: 'java' }
        - { plugin_name: 'maven' }
        - { plugin_name: 'mvnd' }
        - { plugin_name: 'nodejs' }
        - { plugin_name: 'pnpm' }
        - { plugin_name: 'yarn' }
        - { plugin_name: 'azure-cli' }
        - { plugin_name: 'stern' }
        - { plugin_name: 'dapr' }
        - { plugin_name: 'deno' }
    - name: Copy toolset configuration file
      ansible.builtin.copy:
        src: files/.tool-versions
        dest: ~/.tool-versions
        mode: u=rw,g=,o=
    - name: Initialize toolset from file
      changed_when: false
      ansible.builtin.shell: "asdf install"
