---
- name: Workstation setup (macos)
  hosts: localhost
  connection: local
  become: true
  become_user: kunta

  tasks:
    - name: Create applications directory
      ansible.builtin.file:
        path: ~/Applications
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Install homebrew packages
      community.general.homebrew:
        name:
          - gpg
          - podman
          - podman-compose
          - zsh
          - zsh-completions
          - zsh-autosuggestions
          - mise
          - vim
          - zlib
    - name: Install homebrew casks
      community.general.homebrew_cask:
        name:
          - visual-studio-code
          - logi-options+
          - intune-company-portal
          - microsoft-teams
          - rectangle
          - alt-tab
          - raycast
          - betterdisplay
          - stats
          - font-iosevka
          - font-iosevka-nerd-font
          - font-commit-mono
          - font-commit-mono-nerd-font
          - zen-browser
          - microsoft-edge
          - karabiner-elements
          - linearmouse
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=$HOME/Applications"
    - name: Configure keybindings
      ansible.builtin.copy:
        src: .config/karabiner/karabiner.json
        dest: ~/.config/karabiner
        force: no
    - name: Install oh-my-zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: ~/.zshrc
    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        version: v0.7.1
    - name: Enable zsh plugins
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        regexp: '^plugins='
        line: plugins=(git mise zsh-autosuggestions)
    - name: Copy toolset configuration file
      ansible.builtin.copy:
        src: .config/mise/config.toml
        dest: ~/.config/mise
        mode: u=rw,g=,o=
    - name: Initialize toolset from file
      changed_when: false
      ansible.builtin.shell: "mise install"
    - name: Configure git credential helper
      ansible.builtin.shell: "git config --global credential.helper store"
    - name: Configure Terminal.app
      ansible.builtin.shell:
        cmd: |
          defaults write com.apple.Terminal "Default Window Settings" "Pro"
          defaults write com.apple.Terminal "Startup Window Settings" "Pro"
          /usr/libexec/PlistBuddy -c "Set :Window\ Settings:Pro:Font '{{ terminal_font }}'" ~/Library/Preferences/com.apple.Terminal.plist
          /usr/libexec/PlistBuddy -c "Set :Window\ Settings:Pro:columnCount {{ terminal_columns }}" ~/Library/Preferences/com.apple.Terminal.plist
          /usr/libexec/PlistBuddy -c "Set :Window\ Settings:Pro:rowCount {{ terminal_rows }}" ~/Library/Preferences/com.apple.Terminal.plist
      vars:
        terminal_font: "CommitMonoNerdFont-Bold 13"
        terminal_columns: 220
        terminal_rows: 50
